//Aksiyonları yazdığımız kısım

export const CHANGE_CATEGORY = "CHANGE_CATEGORY" 
export const GET_CATEGORİES_SUCCESS = "GET_CATEGORİES_SUCCESS"

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS" 
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const UPTADE_PRODUCT_SUCCESS = "UPTADE_PRODUCT_SUCCESS"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
